version: '3.7'

services:
  tensorflow-train:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: marianferenc/text-classification-demo:latest
    ports:
      - 8888:8888
      - 5000:5000
    volumes:
      - .:/app
    command: >
      sh -c "python inference_service.py"
